"""AI 上下文组装与会话 store。"""

from vnpy_ashare.ai.context.backtest import (
    build_backtest_ai_prompt,
    build_backtest_page_context,
    build_batch_compare_context,
    format_backtest_summary_text,
    resolve_backtest_summary,
    sync_backtest_page_context,
    sync_batch_compare_context,
)
from vnpy_ashare.ai.context.enrichment import enrich_context_with_actions
from vnpy_ashare.ai.context.quote import (
    StockBinding,
    build_assistant_quick_actions,
    build_diagnose_ai_prompt,
    build_floating_stock_quick_actions,
    build_historical_ai_prompt,
    build_positions_ai_prompt,
    build_quote_context,
    build_signal_panel_ai_prompt,
    build_signal_panel_batch_ai_prompt,
    build_signals_ai_prompt,
    build_stock_completion_items,
    build_technical_ai_prompt,
    format_quote_summary,
    resolve_assistant_stock_binding,
)
from vnpy_ashare.ai.context.store import (
    BacktestSummary,
    ScreeningResultContext,
    clear_all,
    get_ai_context,
    get_backtest_summary_dict,
    get_diagnose_result,
    get_market_quotes_cache,
    get_screening_results,
    register_context_listener,
    set_ai_context,
    set_backtest_summary,
    set_diagnose_result,
    set_market_quotes_cache,
    set_screening_results,
    sync_backtest_summary_dict,
)
from vnpy_ashare.ai.context.symbol import parse_stock_symbol
from vnpy_common.ai.protocol import AiContextData, QuickAction, StockCompletionItem

__all__ = [
    "AiContextData",
    "BacktestSummary",
    "QuickAction",
    "ScreeningResultContext",
    "StockBinding",
    "StockCompletionItem",
    "build_floating_stock_quick_actions",
    "resolve_assistant_stock_binding",
    "build_assistant_quick_actions",
    "build_backtest_ai_prompt",
    "build_backtest_page_context",
    "build_batch_compare_context",
    "build_diagnose_ai_prompt",
    "build_historical_ai_prompt",
    "build_quote_context",
    "build_positions_ai_prompt",
    "build_signal_panel_ai_prompt",
    "build_signal_panel_batch_ai_prompt",
    "build_signals_ai_prompt",
    "build_technical_ai_prompt",
    "build_stock_completion_items",
    "clear_all",
    "enrich_context_with_actions",
    "format_backtest_summary_text",
    "format_quote_summary",
    "get_ai_context",
    "get_backtest_summary_dict",
    "get_diagnose_result",
    "get_market_quotes_cache",
    "get_screening_results",
    "parse_stock_symbol",
    "register_context_listener",
    "resolve_backtest_summary",
    "set_ai_context",
    "set_backtest_summary",
    "set_diagnose_result",
    "set_market_quotes_cache",
    "set_screening_results",
    "sync_backtest_page_context",
    "sync_backtest_summary_dict",
    "sync_batch_compare_context",
]
