"""配置：A 股常量、.env ↔ vt_setting.json 桥接。"""

from vnpy_ashare.config.runtime import (
    ASHARE_BACKTEST_DEFAULTS,
    BACKTESTER_SETTING_FILE,
    COMMISSION_RATE,
    EFFECTIVE_RATE,
    EXCHANGE_CN_NAMES,
    EXCHANGE_CN_SHORT,
    LOT_SIZE,
    PRICE_TICK,
    STAMP_TAX_RATE,
    STOCK_EXCHANGES,
    _CN_NAME_TO_EXCHANGE,
    ensure_runtime_config,
    exchange_to_cn,
    format_decimal_field,
    format_vt_symbol_cn,
    is_ashare_exchange,
    normalize_volume,
    write_backtest_defaults,
    _looks_like_futures_config,
)

__all__ = [
    "ASHARE_BACKTEST_DEFAULTS",
    "BACKTESTER_SETTING_FILE",
    "COMMISSION_RATE",
    "EFFECTIVE_RATE",
    "EXCHANGE_CN_NAMES",
    "EXCHANGE_CN_SHORT",
    "LOT_SIZE",
    "PRICE_TICK",
    "STAMP_TAX_RATE",
    "STOCK_EXCHANGES",
    "_CN_NAME_TO_EXCHANGE",
    "ensure_runtime_config",
    "exchange_to_cn",
    "format_decimal_field",
    "format_vt_symbol_cn",
    "is_ashare_exchange",
    "normalize_volume",
    "write_backtest_defaults",
    "_looks_like_futures_config",
]
