"""终端用户偏好（QSettings），供 Service / AI / UI 共用。"""

from vnpy_ashare.config.preferences._settings import SETTINGS_APP, SETTINGS_ORG
from vnpy_ashare.config.preferences.signal_panel_columns import (
    DEFAULT_VISIBLE_OPTIONAL_KEYS,
    SIGNAL_PANEL_FIXED_KEYS,
    SIGNAL_PANEL_OPTIONAL_COLUMNS,
    SIGNAL_PANEL_OPTIONAL_KEYS,
    normalize_visible_optional_keys,
    resolve_signal_panel_columns,
)
from vnpy_ashare.config.preferences.watchlist_position import (
    POSITION_PANEL_COLLAPSED_HEIGHT,
    POSITION_PANEL_DEFAULT_HEIGHT,
    WatchlistPositionConfig,
    load_position_panel_enabled,
    load_position_panel_expanded,
    load_watchlist_position_config,
    save_position_panel_enabled,
    save_position_panel_expanded,
    save_watchlist_position_config,
)
from vnpy_ashare.config.preferences.watchlist_signal import (
    DEFAULT_CLASS,
    DEFAULT_FAST,
    DEFAULT_SLOW,
    SIGNAL_PANEL_MAX_SYMBOLS,
    WatchlistSignalConfig,
    load_center_splitter_sizes,
    load_signal_panel_columns,
    load_signal_panel_enabled,
    load_signal_panel_expanded,
    load_signal_panel_symbols,
    load_watchlist_signal_config,
    normalize_signal_panel_symbols,
    save_center_splitter_sizes,
    save_signal_panel_columns,
    save_signal_panel_enabled,
    save_signal_panel_expanded,
    save_signal_panel_symbols,
    save_watchlist_signal_config,
)

__all__ = [
    "DEFAULT_CLASS",
    "DEFAULT_FAST",
    "DEFAULT_SLOW",
    "DEFAULT_VISIBLE_OPTIONAL_KEYS",
    "POSITION_PANEL_COLLAPSED_HEIGHT",
    "POSITION_PANEL_DEFAULT_HEIGHT",
    "SETTINGS_APP",
    "SETTINGS_ORG",
    "SIGNAL_PANEL_FIXED_KEYS",
    "SIGNAL_PANEL_MAX_SYMBOLS",
    "SIGNAL_PANEL_OPTIONAL_COLUMNS",
    "SIGNAL_PANEL_OPTIONAL_KEYS",
    "WatchlistPositionConfig",
    "WatchlistSignalConfig",
    "load_center_splitter_sizes",
    "load_position_panel_enabled",
    "load_position_panel_expanded",
    "load_signal_panel_columns",
    "load_signal_panel_enabled",
    "load_signal_panel_expanded",
    "load_signal_panel_symbols",
    "load_watchlist_signal_config",
    "load_watchlist_position_config",
    "normalize_signal_panel_symbols",
    "normalize_visible_optional_keys",
    "resolve_signal_panel_columns",
    "save_center_splitter_sizes",
    "save_position_panel_enabled",
    "save_position_panel_expanded",
    "save_signal_panel_columns",
    "save_signal_panel_enabled",
    "save_signal_panel_expanded",
    "save_signal_panel_symbols",
    "save_watchlist_position_config",
    "save_watchlist_signal_config",
]
