"""并行 I/O worker 环境变量键名与默认值。

环境变量模板见仓库根目录 ``.env.example`` 中「并行 I/O worker」一节。
"""

from __future__ import annotations

ENV_DOWNLOAD_MAX_WORKERS = "DOWNLOAD_MAX_WORKERS"
DEFAULT_DOWNLOAD_MAX_WORKERS = 3
CAP_DOWNLOAD_MAX_WORKERS = 6

ENV_MCP_INTRADAY_FLOW_MAX_WORKERS = "MCP_INTRADAY_FLOW_MAX_WORKERS"
DEFAULT_MCP_INTRADAY_FLOW_MAX_WORKERS = 4
CAP_MCP_INTRADAY_FLOW_MAX_WORKERS = 8

ENV_CONCEPT_MEMBER_MAX_WORKERS = "CONCEPT_MEMBER_MAX_WORKERS"
DEFAULT_CONCEPT_MEMBER_MAX_WORKERS = 3
CAP_CONCEPT_MEMBER_MAX_WORKERS = 6

ENV_CONCEPT_PREFETCH_MAX_WORKERS = "CONCEPT_PREFETCH_MAX_WORKERS"
DEFAULT_CONCEPT_PREFETCH_MAX_WORKERS = 2
CAP_CONCEPT_PREFETCH_MAX_WORKERS = 2

ENV_SECTOR_FLOW_SYNC_MAX_WORKERS = "SECTOR_FLOW_SYNC_MAX_WORKERS"
DEFAULT_SECTOR_FLOW_SYNC_MAX_WORKERS = 5
CAP_SECTOR_FLOW_SYNC_MAX_WORKERS = 10

ENV_MONEYFLOW_PREFETCH_MAX_WORKERS = "MONEYFLOW_PREFETCH_MAX_WORKERS"
DEFAULT_MONEYFLOW_PREFETCH_MAX_WORKERS = 5
CAP_MONEYFLOW_PREFETCH_MAX_WORKERS = 10

ENV_TUSHARE_ANCHOR_PREFETCH_MAX_WORKERS = "TUSHARE_ANCHOR_PREFETCH_MAX_WORKERS"
DEFAULT_TUSHARE_ANCHOR_PREFETCH_MAX_WORKERS = 4
CAP_TUSHARE_ANCHOR_PREFETCH_MAX_WORKERS = 8

ENV_TUSHARE_PREFETCH_STAGE_MAX_WORKERS = "TUSHARE_PREFETCH_STAGE_MAX_WORKERS"
DEFAULT_TUSHARE_PREFETCH_STAGE_MAX_WORKERS = 2
CAP_TUSHARE_PREFETCH_STAGE_MAX_WORKERS = 4

ENV_AVG_TURNOVER_PREFETCH_MAX_WORKERS = "AVG_TURNOVER_PREFETCH_MAX_WORKERS"
DEFAULT_AVG_TURNOVER_PREFETCH_MAX_WORKERS = 5
CAP_AVG_TURNOVER_PREFETCH_MAX_WORKERS = 10

ENV_CONTINUATION_BATCH_MAX_WORKERS = "CONTINUATION_BATCH_MAX_WORKERS"
DEFAULT_CONTINUATION_BATCH_MAX_WORKERS = 4
CAP_CONTINUATION_BATCH_MAX_WORKERS = 8

ENV_RELATIVE_INDEX_ENRICH_MAX_WORKERS = "RELATIVE_INDEX_ENRICH_MAX_WORKERS"
DEFAULT_RELATIVE_INDEX_ENRICH_MAX_WORKERS = 4
CAP_RELATIVE_INDEX_ENRICH_MAX_WORKERS = 8

ENV_INTRADAY_SEAL_TIME_MAX_WORKERS = "INTRADAY_SEAL_TIME_MAX_WORKERS"
DEFAULT_INTRADAY_SEAL_TIME_MAX_WORKERS = 4
CAP_INTRADAY_SEAL_TIME_MAX_WORKERS = 8

ENV_RADAR_BOARD_MAX_WORKERS = "RADAR_BOARD_MAX_WORKERS"
DEFAULT_RADAR_BOARD_MAX_WORKERS = 4
CAP_RADAR_BOARD_MAX_WORKERS = 8
