"""选股配方相关默认值与环境变量键名。"""

from __future__ import annotations

# 硬过滤
DEFAULT_MIN_AMOUNT_YUAN = 30_000_000.0  # 3000 万元
# Tushare daily_basic.total_mv 单位为万元；50 亿 = 500000 万元
DEFAULT_MIN_TOTAL_MV_WAN = 500_000.0
DEFAULT_MIN_LISTING_DAYS = 60

# 行情新鲜度
DEFAULT_MAX_QUOTE_AGE_SECONDS = 90

# 维度打分
DEFAULT_METRIC_SCORE_BLEND = 0.5
DEFAULT_VOLUME_LIQUIDITY_DEDUP_FACTOR = 0.5
DEFAULT_RECIPE_DIMENSION_MAX_WORKERS = 4

# 环境变量键（RECIPE_*，环境变量优先于 QSettings）
ENV_MIN_AMOUNT_YUAN = "RECIPE_MIN_AMOUNT_YUAN"
ENV_EXCLUDE_ST = "RECIPE_EXCLUDE_ST"
ENV_EXCLUDE_SUSPENDED = "RECIPE_EXCLUDE_SUSPENDED"
ENV_MIN_TOTAL_MV_WAN = "RECIPE_MIN_TOTAL_MV_WAN"
ENV_EXCLUDE_NEW_LISTING = "RECIPE_EXCLUDE_NEW_LISTING"
ENV_MIN_LISTING_DAYS = "RECIPE_MIN_LISTING_DAYS"
ENV_EXCLUDE_LIMIT_BOARD = "RECIPE_EXCLUDE_LIMIT_BOARD"
ENV_EXCLUDE_ONE_WORD = "RECIPE_EXCLUDE_ONE_WORD"
ENV_ALLOWED_INDUSTRIES = "RECIPE_ALLOWED_INDUSTRIES"
ENV_ALLOWED_MARKET_BOARDS = "RECIPE_ALLOWED_MARKET_BOARDS"
ENV_QUOTE_MAX_AGE_SEC = "RECIPE_QUOTE_MAX_AGE_SEC"
ENV_SENTIMENT_GATE = "RECIPE_SENTIMENT_GATE"
ENV_METRIC_SCORE_BLEND = "RECIPE_METRIC_SCORE_BLEND"
ENV_VOLUME_LIQUIDITY_DEDUP_FACTOR = "RECIPE_VOLUME_LIQUIDITY_DEDUP_FACTOR"
ENV_DIMENSION_MAX_WORKERS = "RECIPE_DIMENSION_MAX_WORKERS"
