"""出站通知事件 ID 与默认订阅。"""

from __future__ import annotations

NOTIFY_EVENT_SCREENER_INTRADAY_DONE = "screener_intraday_done"
NOTIFY_EVENT_SCREENER_POST_CLOSE_DONE = "screener_post_close_done"
NOTIFY_EVENT_SCHEDULER_JOB_FAILED = "scheduler_job_failed"
NOTIFY_EVENT_MANUAL_TEST = "manual_test"
NOTIFY_EVENT_EMOTION_STAGE_CHANGE = "emotion_stage_change"
NOTIFY_EVENT_RISK_GATE_CHANGE = "risk_gate_change"
NOTIFY_EVENT_POSITION_ALERT = "position_alert"
NOTIFY_EVENT_JOURNAL_VIOLATION = "journal_violation"
NOTIFY_EVENT_RADAR_LEADER_READY = "radar_leader_ready"

DEFAULT_EVENT_SUBSCRIPTIONS: dict[str, bool] = {
    NOTIFY_EVENT_SCREENER_INTRADAY_DONE: True,
    NOTIFY_EVENT_SCREENER_POST_CLOSE_DONE: False,
    NOTIFY_EVENT_SCHEDULER_JOB_FAILED: True,
    NOTIFY_EVENT_EMOTION_STAGE_CHANGE: True,
    NOTIFY_EVENT_RISK_GATE_CHANGE: True,
    NOTIFY_EVENT_POSITION_ALERT: False,
    NOTIFY_EVENT_JOURNAL_VIOLATION: False,
    NOTIFY_EVENT_RADAR_LEADER_READY: False,
}
